import { build as esbuild } from "esbuild";
import { readFile } from "fs/promises";
import path from "path";

// Dependencies that should be bundled (not externalized)
// Everything else will be externalized to reduce bundle size
const allowlist = [
  "express",
  "express-session",
  "multer",
  "zod",
  "zod-validation-error",
  "date-fns",
];

async function buildVercelApi() {
  console.log("building Vercel API function...");
  
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: ["api/index.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: "api/index.js",
    define: {
      "process.env.NODE_ENV": '"production"',
      "process.env.VERCEL": '"1"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
    packages: "bundle",
    resolveExtensions: [".ts", ".js", ".json"],
    alias: {
      "@shared": path.resolve(process.cwd(), "shared"),
    },
    banner: {
      js: "// This file is auto-generated by build-vercel.ts",
    },
  });
  
  console.log("✓ Vercel API function built");
}

buildVercelApi().catch((err) => {
  console.error(err);
  process.exit(1);
});
